nombre_curso = "Ultimate Python"
nombre1 = "Hola"
NOMBRE_CURSO = "Mundo"
NoMbRe_CuRsO = "spd"
nombreCurso = "emergencia"
print = (nombre_curso, nombre1, NOMBRE_CURSO)
alumnos = 5000
puntaje = 9.9
publicado = False
