animal = "  pollo FEliz  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("FE"))
print(animal.find("g"))
print(animal.replace("o", "a"))
print("FE" in animal)
print("FE" not in animal)
